<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="MathVoyager.Tests/**" />
    <Content Remove="MathVoyager.Tests/**" />
    <None Remove="MathVoyager.Tests/**" />
    <EmbeddedResource Remove="MathVoyager.Tests/**" />
    <Compile Remove="android/**" />
    <Content Remove="android/**" />
    <None Remove="android/**" />
    <EmbeddedResource Remove="android/**" />
    <Compile Remove="publish/**" />
    <Content Remove="publish/**" />
    <None Remove="publish/**" />
    <EmbeddedResource Remove="publish/**" />
    <Compile Remove="node_modules/**" />
    <Content Remove="node_modules/**" />
    <None Remove="node_modules/**" />
    <EmbeddedResource Remove="node_modules/**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="8.0.25" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="8.0.25" PrivateAssets="all" />
  </ItemGroup>

</Project>
